// sonicthefighters - ReXGlue Recompiled Project
// Generated by: rexglue migrate
//
// This file is SDK-managed. Customizations go in virtual hook overrides.
// Running 'rexglue migrate' will overwrite this file.

#include "generated/sonicthefighters_config.h"
#include "generated/sonicthefighters_init.h"
#include <rex/ppc/function.h>
#include <rex/rex_app.h>

class SonicthefightersApp : public rex::ReXApp {
 public:
  using rex::ReXApp::ReXApp;

  static std::unique_ptr<rex::ui::WindowedApp> Create(
      rex::ui::WindowedAppContext& ctx) {
    return std::unique_ptr<SonicthefightersApp>(new SonicthefightersApp(ctx, "sonicthefighters",
        {PPC_CODE_BASE, PPC_CODE_SIZE, PPC_IMAGE_BASE,
         PPC_IMAGE_SIZE, PPCFuncMappings}));
  }
};

REX_DEFINE_APP(sonicthefighters, SonicthefightersApp::Create)

PPC_STUB(__imp__XamUserCreateStatsEnumerator);
PPC_STUB(__imp__XamShowFriendsUI);
PPC_STUB(__imp__XamShowQuickChatUI);
PPC_STUB(__imp__XamShowGamerCardUIForXUID);
PPC_STUB(__imp__XamShowAchievementsUI);
PPC_STUB(__imp__XamShowPlayerReviewUI);
PPC_STUB(__imp__XamShowMarketplaceUI);
PPC_STUB(__imp__XamShowGameInviteUI);
PPC_STUB(__imp__MmLockAndMapSegmentArray);
PPC_STUB(__imp__MmUnlockAndUnmapSegmentArray);
PPC_STUB(__imp__NetDll_XNetConnect);
PPC_STUB(__imp__NetDll_XNetGetConnectStatus);
PPC_STUB(__imp__NetDll_XNetQosLookup);
PPC_STUB(__imp__NetDll_WSAGetOverlappedResult);
PPC_STUB(__imp__XNetLogonGetTitleID);
PPC_STUB(__imp__XamVoiceSubmitPacket);
PPC_STUB(__imp__XAudioGetDuckerLevel);
PPC_STUB(__imp__XAudioGetDuckerReleaseTime);
PPC_STUB(__imp__XAudioGetDuckerAttackTime);
PPC_STUB(__imp__XAudioGetDuckerHoldTime);
PPC_STUB(__imp__XAudioGetDuckerThreshold);
PPC_STUB(__imp__IoInvalidDeviceRequest);
PPC_STUB(__imp__ObReferenceObject);
PPC_STUB(__imp__IoDeleteDevice);
PPC_STUB(__imp__IoCompleteRequest);
PPC_STUB(__imp__NtWriteFileGather);
PPC_STUB(__imp__RtlUpcaseUnicodeChar);
PPC_STUB(__imp__ObIsTitleObject);
PPC_STUB(__imp__IoCheckShareAccess);
PPC_STUB(__imp__IoSetShareAccess);
PPC_STUB(__imp__IoRemoveShareAccess);